version: "3.7"
services:
  
  flask:
    build: flask
    restart: always

  nginx:
    build: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    environment:
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx
      - FLASK_HOST=flask
      - FLASK_PORT=5000    
    volumes: 
      - /etc/nginx/ssl.crt/certificate.crt:/etc/nginx/ssl.crt/certificate.crt
      - /etc/nginx/ssl.crt/private.key:/etc/nginx/ssl.crt/private.key
